# Generated by Django 4.0.3 on 2022-03-11 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mgt', '0002_remove_staff_user_staff_first_name_staff_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.CharField(default='aastu_staff@aastu.edu', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='last_login',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default='serR33%sho9s2', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(default='09000000', max_length=30, null=True),
        ),
    ]
