# Generated by Django 4.0.3 on 2022-03-11 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgt', '0003_staff_date_joined_staff_email_staff_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgt.role')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgt.staff')),
            ],
            options={
                'db_table': 'staff_role',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='roles',
            field=models.ManyToManyField(through='mgt.StaffRole', to='mgt.role'),
        ),
    ]
